# 인덱싱과 슬라이싱을 이용한 배열의 원소 조회

## 배열 인덱싱(Indexing)
- ### index
    - 배열내의 원소의 식별번호
    - 0부터 시작
- ### indexing 
    – index를 이용해 원소 조회
    - [] 표기법 사용
- ### 구문 
    - ndarray[index]
    - 양수는 지정한 index의 값을 조회한다. 
    - 음수는 뒤부터 조회한다. 
        - 마지막 index가 -1
    - 2차원배열의 경우 
        - arr[행index, 열index]
        - 파이썬 리스트와 차이점 (list[행][열])
    - N차원 배열의 경우
        - arr[0축 index, 1축 index, ..., n축 index]
- ### 팬시(fancy) 인덱싱
    - **여러개의 원소를 한번에 조회**할 경우 리스트에 담아 전달한다.
    - 다차원 배열의 경우 각 축별로 list로 지정
    - `arr[[1,2,3,4,5]]`
        - 1차원 배열(vector): 1,2,3,4,5 번 index의 원소들 한번에 조회
    - `arr[[0,3],[ 1,4]]`
        - [0,3] - 1번축 index list, [1,4] - 2번축 index list
        - 2차원 배열(matrix): [0,1], [3,4] 의 원소들 조회

In [3]:
import numpy as np

In [1]:
l = [
    [1,2,3],
    [10,20,30]
]
l

[[1, 2, 3], [10, 20, 30]]

In [2]:
print(l[0])
print(l[0][1])

[1, 2, 3]
2


In [4]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# 1개 값 조회
a[0]

0

In [6]:
print(a[1], a[5])

1 5


In [7]:
a2 = np.arange(12).reshape(2,2,3)
a2.shape

(2, 2, 3)

In [8]:
a2

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [9]:
# 7조회
a2[1, 0, 1]

7

In [10]:
# 5조회
a2[0, 1, 2] #a2[0][1][2]랑 같음. 리스트는 반점 찍는 표현 안 됨

5

In [12]:
# fancy indexing : 한 번에 여러 개의 값을 조회
# 2, 5, 7 index에 있는 값 조회
a[[2, 5, 7]]  # 리스트로 조회할 inde들을 묶어준다. 안쪽 대괄호는 리스트, 바깥쪽 대괄호는 indexer

array([2, 5, 7])

In [13]:
arr = np.array([[1,2,3], [10,20,30]])
arr.shape

(2, 3)

In [14]:
arr

array([[ 1,  2,  3],
       [10, 20, 30]])

In [15]:
arr[0, 0]

1

In [16]:
arr[1, 1]

20

In [20]:
# 1, 30, 20을 한 번에 조회
# 배열[axis=0의 index, axis=1의 index]
arr[[0, 1, 1], [0, 2, 1]]

array([ 1, 30, 20])

In [21]:
a2

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [22]:
# 1, 8, 11 조회
a2[[0, 1, 1], [0, 0, 1], [1, 2, 2]]

array([ 1,  8, 11])

In [23]:
a2[[0,1], [0,1]] # 배열로 조회도 가능

array([[ 0,  1,  2],
       [ 9, 10, 11]])

## 슬라이싱
- 배열의 부분 집합을 하위배열로 조회 및 변경하는 방식
- ndarry[start : stop : step ], start, stop, step 생략 가능
    - start : 시작 인덱스. 기본값 0
    - stop : 끝 index. stop에 지정된 값은 포함하지 않는다. 기본값 마지막 index
    - step : 증감 간격. 기본값 1

In [33]:
a = np.arange(100)
print(a)
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
(100,)


In [34]:
# 10 ~ 49, step: +2
a[10:50:2]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [35]:
# 0 ~ 49, step: +5
a[:50:5]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [36]:
# 50 ~ 끝, step: +10
a[50::10]

array([50, 60, 70, 80, 90])

In [37]:
# 1 ~ 9, step: +1
a[1:10:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a[99:10:-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11])

In [42]:
a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [43]:
a[::-5]

array([99, 94, 89, 84, 79, 74, 69, 64, 59, 54, 49, 44, 39, 34, 29, 24, 19,
       14,  9,  4])

### 다차원 배열 슬라이싱
- 각 축에 slicing 문법 적용
- 2차원의 경우
    - arr [행 slicing, 열 slicing]
        - `arr[:3, :]`
    - `,` 로 행과 열을 구분한 다중 슬라이싱 사용
- 다차원의 경우
    - arr[0축 slicing, 1축 slicing, ..., n축 slicing]
- slicing과 indexing 문법은 같이 쓸 수 있다.
- 모든 축에 index를 지정할 필요는 없다.

In [ ]:
# 0번 축은 1~4, 1번 축은 2~3을 조회하겠다는 의미 
arr[1:5, 2:4]

In [45]:
a = np.arange(48).reshape(6, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [46]:
# axis=0 1~4, axis=1 1~5, step:+1(default)
a[1:5, 1:6]

array([[ 9, 10, 11, 12, 13],
       [17, 18, 19, 20, 21],
       [25, 26, 27, 28, 29],
       [33, 34, 35, 36, 37]])

In [48]:
a[1:5, ::-2]

array([[15, 13, 11,  9],
       [23, 21, 19, 17],
       [31, 29, 27, 25],
       [39, 37, 35, 33]])

In [49]:
# axis=0의 모든 index에서 axis=1의 0, 2에 해당하는 index만 조회
a[:, [0,2]]

array([[ 0,  2],
       [ 8, 10],
       [16, 18],
       [24, 26],
       [32, 34],
       [40, 42]])

### 슬라이싱은 원본에 대한 View 
- slicing한 결과는 새로운 배열을 생성하는 것이 아니라 기존 배열을 참조한다.
- slicing한 배열의 원소를 변경하면 원본 배열의 것도 바뀐다.
- 배열.copy()
    - 배열을 복사한 새로운 배열 생성
    - 복사후 처리하면 원본이 바뀌지 않는다.

In [50]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [52]:
b = a[1:5, 1:6]
b

array([[ 9, 10, 11, 12, 13],
       [17, 18, 19, 20, 21],
       [25, 26, 27, 28, 29],
       [33, 34, 35, 36, 37]])

In [54]:
b[0,0] = 9000 # 원본 배열 a의 값도 같이 변경됨. shallow copy
b

array([[9000,   10,   11,   12,   13],
       [  17,   18,   19,   20,   21],
       [  25,   26,   27,   28,   29],
       [  33,   34,   35,   36,   37]])

In [55]:
a

array([[   0,    1,    2,    3,    4,    5,    6,    7],
       [   8, 9000,   10,   11,   12,   13,   14,   15],
       [  16,   17,   18,   19,   20,   21,   22,   23],
       [  24,   25,   26,   27,   28,   29,   30,   31],
       [  32,   33,   34,   35,   36,   37,   38,   39],
       [  40,   41,   42,   43,   44,   45,   46,   47]])

In [56]:
c = a[1:5, 1:6].copy() # ndarray.copy() => 배열을 복사한 새로운 배열 반환. deep copy
c

array([[9000,   10,   11,   12,   13],
       [  17,   18,   19,   20,   21],
       [  25,   26,   27,   28,   29],
       [  33,   34,   35,   36,   37]])

In [57]:
c[0,0] = 9
c

array([[ 9, 10, 11, 12, 13],
       [17, 18, 19, 20, 21],
       [25, 26, 27, 28, 29],
       [33, 34, 35, 36, 37]])

In [58]:
a

array([[   0,    1,    2,    3,    4,    5,    6,    7],
       [   8, 9000,   10,   11,   12,   13,   14,   15],
       [  16,   17,   18,   19,   20,   21,   22,   23],
       [  24,   25,   26,   27,   28,   29,   30,   31],
       [  32,   33,   34,   35,   36,   37,   38,   39],
       [  40,   41,   42,   43,   44,   45,   46,   47]])

## boolean indexing
- Index 연산자에 Boolean 배열을 넣으면 True인 index의 값만 조회 (False가 있는 index는 조회하지 않는다.)
- ndarray내의 원소 중에서 원하는 조건의 값들만 조회할 때 사용

In [60]:
a = np.arange(3)
a

array([0, 1, 2])

In [61]:
b = [True, False, True]   # bool 값을 가진 리스트(배열도 쓰지만 리스트를 많이 씀)
a[b]   # True인 인덱스만 조회. masking

array([0, 2])

In [62]:
a[[True, False, True]]

array([0, 2])

In [63]:
a + 10

array([10, 11, 12])

In [64]:
a * 10

array([ 0, 10, 20])

In [65]:
a > 10

array([False, False, False])

In [68]:
print(a2)
print(a2 + 10)
print(a2 > 5)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]]]
[[[False False False]
  [False False False]]

 [[ True  True  True]
  [ True  True  True]]]


In [69]:
# 배열 a의 원소 중 1 이상인 값들만 조회 => 특정 조건을 만족시키는 원소들만 조회할 때 boolean indexing을 사용
a[a>=1]

array([1, 2])

In [70]:
b = np.random.randint(100, size=100)
b

array([75, 86, 57, 56, 26, 28,  3, 98, 29, 30, 11, 83, 39, 13, 53, 27, 21,
       82, 93, 86, 61, 80, 93, 35, 42,  3, 92, 34, 96, 87,  8, 86, 33, 43,
        3, 37, 15, 27,  9, 73,  0, 95, 39, 55, 70, 35, 48, 44, 18, 70, 88,
       12, 94, 73, 91, 81, 62, 82, 57, 13, 99, 49, 93, 96, 83, 29, 80, 38,
       52, 62, 14,  2, 89, 38,  9, 26, 94, 33, 92,  6,  7, 25, 19, 30, 48,
       82, 78, 57, 80,  5,  1, 22, 91, 63, 37, 75, 23, 98, 85, 72])

In [75]:
c = b[b >= 50]
c.shape

(50,)

In [77]:
b2 = b.reshape(2,50)
b2

array([[75, 86, 57, 56, 26, 28,  3, 98, 29, 30, 11, 83, 39, 13, 53, 27,
        21, 82, 93, 86, 61, 80, 93, 35, 42,  3, 92, 34, 96, 87,  8, 86,
        33, 43,  3, 37, 15, 27,  9, 73,  0, 95, 39, 55, 70, 35, 48, 44,
        18, 70],
       [88, 12, 94, 73, 91, 81, 62, 82, 57, 13, 99, 49, 93, 96, 83, 29,
        80, 38, 52, 62, 14,  2, 89, 38,  9, 26, 94, 33, 92,  6,  7, 25,
        19, 30, 48, 82, 78, 57, 80,  5,  1, 22, 91, 63, 37, 75, 23, 98,
        85, 72]])

In [79]:
(b2 >= 50).shape

(2, 50)

In [80]:
# 원본 배열의 차원과 관련 없이 boolean indexing 적용하고 나면 True값들만 1차원 배열에 모아서 반환
b2[b2 >= 50]

array([75, 86, 57, 56, 98, 83, 53, 82, 93, 86, 61, 80, 93, 92, 96, 87, 86,
       73, 95, 55, 70, 70, 88, 94, 73, 91, 81, 62, 82, 57, 99, 93, 96, 83,
       80, 52, 62, 89, 94, 92, 82, 78, 57, 80, 91, 63, 75, 98, 85, 72])

In [81]:
b = np.random.randint(100, size=100)
b

array([17, 35, 49, 91, 13, 94, 81, 36, 25, 75, 39, 69, 26, 30, 80, 19, 40,
       12, 64, 67, 14,  1, 25, 27, 51, 63,  6, 81, 43, 76, 23, 40,  9, 26,
       19,  0, 83, 55, 90, 28, 41, 34, 69, 52, 87, 94, 55, 71, 58, 14, 36,
       50, 70, 54, 23, 76, 89, 71, 15,  8, 25, 37, 34, 63, 77, 65, 65,  1,
       67, 88, 90, 49, 93, 16, 61, 50, 94, 34, 55, 82, 21, 98, 94, 54, 36,
       60, 95, 93, 59,  3, 74, 39, 88, 94, 64, 14, 43,  1, 84, 98])

In [85]:
# 50 ~ 70 사이의 정수만 조회?
# 파이썬 논리 연산자를 numpy에서는 사용 불가 (and, or)
# 대신 기호를 사용해야 함. &, |, ~(not)
# 피연산자는 반드시 소괄호로 묶어 줘야 한다.

(b >= 50) & (b <= 70)

array([False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
        True,  True, False, False, False, False,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False,  True,  True, False,
       False,  True, False,  True, False, False,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
        True, False,  True,  True, False,  True, False, False, False,
       False, False,  True,  True, False, False,  True, False, False,
       False, False,  True, False,  True, False, False,  True, False,
       False, False, False, False,  True, False, False, False, False,
       False])

In [86]:
b[(b >= 50) & (b <= 70)]

array([69, 64, 67, 51, 63, 55, 69, 52, 55, 58, 50, 70, 54, 63, 65, 65, 67,
       61, 50, 55, 54, 60, 59, 64])

In [87]:
b[~(b>50)]

array([17, 35, 49, 13, 36, 25, 39, 26, 30, 19, 40, 12, 14,  1, 25, 27,  6,
       43, 23, 40,  9, 26, 19,  0, 28, 41, 34, 14, 36, 50, 23, 15,  8, 25,
       37, 34,  1, 49, 16, 50, 34, 21, 36,  3, 39, 14, 43,  1])

### np.where()
- np.where(boolean 배열 or 리스트) - True인 index를 반환
- boolean연산과 같이쓰면 특정 조건을 만족하는 원소의 index조회됨.
- np.where(boolean 배열, True를 대체할 값, False를 대체할 값)
    - True와 False를 다른 값으로 변경한다.

In [89]:
l = [True, False, True, True]
np.where(l)  # 리스트에서 True값들의 index들을 반환(반환 타입은 튜플)

(array([0, 2, 3], dtype=int64),)

In [90]:
np.where(l, '참', '거짓')

array(['참', '거짓', '참', '참'], dtype='<U2')

In [92]:
# True는 참으로 바꾸고 False는 원래 값 쓰겠다는 뜻
np.where(l, '참', l)

array(['참', 'False', '참', '참'], dtype='<U5')

In [94]:
b[b >= 50]   # b의 원소 중 50 이상인 값들을 조회
np.where(b >= 50)   # b의 원소 중 50 이상인 값들의 index 조회

(array([ 3,  5,  6,  9, 11, 14, 18, 19, 24, 25, 27, 29, 36, 37, 38, 42, 43,
        44, 45, 46, 47, 48, 51, 52, 53, 55, 56, 57, 63, 64, 65, 66, 68, 69,
        70, 72, 74, 75, 76, 78, 79, 81, 82, 83, 85, 86, 87, 88, 90, 92, 93,
        94, 98, 99], dtype=int64),)

In [95]:
np.where(b>=50, '50이상', '50미만')

array(['50미만', '50미만', '50미만', '50이상', '50미만', '50이상', '50이상', '50미만',
       '50미만', '50이상', '50미만', '50이상', '50미만', '50미만', '50이상', '50미만',
       '50미만', '50미만', '50이상', '50이상', '50미만', '50미만', '50미만', '50미만',
       '50이상', '50이상', '50미만', '50이상', '50미만', '50이상', '50미만', '50미만',
       '50미만', '50미만', '50미만', '50미만', '50이상', '50이상', '50이상', '50미만',
       '50미만', '50미만', '50이상', '50이상', '50이상', '50이상', '50이상', '50이상',
       '50이상', '50미만', '50미만', '50이상', '50이상', '50이상', '50미만', '50이상',
       '50이상', '50이상', '50미만', '50미만', '50미만', '50미만', '50미만', '50이상',
       '50이상', '50이상', '50이상', '50미만', '50이상', '50이상', '50이상', '50미만',
       '50이상', '50미만', '50이상', '50이상', '50이상', '50미만', '50이상', '50이상',
       '50미만', '50이상', '50이상', '50이상', '50미만', '50이상', '50이상', '50이상',
       '50이상', '50미만', '50이상', '50미만', '50이상', '50이상', '50이상', '50미만',
       '50미만', '50미만', '50이상', '50이상'], dtype='<U4')

In [96]:
# 70 이상인 값들을 모두 70으로 변환, 70 이하는 유지
np.where(b>=70, 70, b)

array([17, 35, 49, 70, 13, 70, 70, 36, 25, 70, 39, 69, 26, 30, 70, 19, 40,
       12, 64, 67, 14,  1, 25, 27, 51, 63,  6, 70, 43, 70, 23, 40,  9, 26,
       19,  0, 70, 55, 70, 28, 41, 34, 69, 52, 70, 70, 55, 70, 58, 14, 36,
       50, 70, 54, 23, 70, 70, 70, 15,  8, 25, 37, 34, 63, 70, 65, 65,  1,
       67, 70, 70, 49, 70, 16, 61, 50, 70, 34, 55, 70, 21, 70, 70, 54, 36,
       60, 70, 70, 59,  3, 70, 39, 70, 70, 64, 14, 43,  1, 70, 70])

In [97]:
c = np.arange(12).reshape(3, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
np.where(c>5)
# 반환된 튜플 형식: (axis=0의 index 배열, axis=1의 index 배열)

(array([1, 1, 2, 2, 2, 2], dtype=int64),
 array([2, 3, 0, 1, 2, 3], dtype=int64))

In [99]:
c>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [100]:
d = np.arange(12).reshape(2, 2, 3)
d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [101]:
np.where(d>7)

(array([1, 1, 1, 1], dtype=int64),
 array([0, 1, 1, 1], dtype=int64),
 array([2, 0, 1, 2], dtype=int64))

- 2차원도 마찬가지
    - 단 where는 축별로 배열이 반환된다. [0,1], [2,3] => (0,2)  (1,3)
    - 보통 Vector에 적용한다.

### 기타
- np.any(boolean 배열)
    - 배열에 True가 하나라도 있으면 True 반환
- np.all(boolean 배열)
    - 배열의 모든 원소가 True이면 True 반환

In [102]:
b

array([17, 35, 49, 91, 13, 94, 81, 36, 25, 75, 39, 69, 26, 30, 80, 19, 40,
       12, 64, 67, 14,  1, 25, 27, 51, 63,  6, 81, 43, 76, 23, 40,  9, 26,
       19,  0, 83, 55, 90, 28, 41, 34, 69, 52, 87, 94, 55, 71, 58, 14, 36,
       50, 70, 54, 23, 76, 89, 71, 15,  8, 25, 37, 34, 63, 77, 65, 65,  1,
       67, 88, 90, 49, 93, 16, 61, 50, 94, 34, 55, 82, 21, 98, 94, 54, 36,
       60, 95, 93, 59,  3, 74, 39, 88, 94, 64, 14, 43,  1, 84, 98])

In [104]:
# 배열 b에 99 이상인 값이 하나라도 있는지 여부 확인
np.any(b >= 99)

False

In [105]:
np.any(b >= 90)

True

In [106]:
# 배열 b의 모든 원소가 90 이상인지 확인
np.all(b >= 90)

False

In [108]:
np.all(b >= 0)

True

### 정렬
- np.sort(arr): 매개변수로 전달한 배열을 정렬한 새로운 배열을 반환
    - arr 원본은 변경되지 않는다.
- ndarray.sort(): 배열객체 자체를 직접 sort, 원본을 바꿔버린다.
- np.argsort(arr): 정렬 후 index를 반환

In [109]:
x = np.array([4, 1, 6, 9, 2])
x

array([4, 1, 6, 9, 2])

In [114]:
y = np.sort(x)   # x를 정렬한 원소들을 가지는 새로운 배열을 반환
y

array([1, 2, 4, 6, 9])

In [113]:
x

array([4, 1, 6, 9, 2])

In [118]:
x.sort()

In [119]:
x

array([1, 2, 4, 6, 9])

In [121]:
z = np.array([4, 1, 6, 9, 2])
# 내림차순 정렬 -> slicing 이용
np.sort(z)[::-1]

array([9, 6, 4, 2, 1])

In [126]:
print(z * -1)
print(-z)
print(np.sort(-z))
print(-np.sort(-z))

[-4 -1 -6 -9 -2]
[-4 -1 -6 -9 -2]
[-9 -6 -4 -2 -1]
[9 6 4 2 1]


In [127]:
a = np.array([0.1, 0.7, 0.4])
a

array([0.1, 0.7, 0.4])

In [129]:
# 오름차순 정렬했을 때 먼저 오는 index - 0, 2, 1
sort_idx = np.argsort(a)
sort_idx

array([0, 2, 1], dtype=int64)

In [130]:
a[sort_idx]

array([0.1, 0.4, 0.7])

### 다차원 배열 정렬
- np.sort(배열, axis=기준 축) 기준 축 생략 시 마지막 축을 기준으로 정렬

In [131]:
l = [
    [1, 0, 5],
    [0, 10, 2],
    [8, 7, 6]
]
arr = np.array(l)
arr.shape

(3, 3)

In [132]:
arr

array([[ 1,  0,  5],
       [ 0, 10,  2],
       [ 8,  7,  6]])

In [133]:
np.sort(arr, axis=0)

array([[ 0,  0,  2],
       [ 1,  7,  5],
       [ 8, 10,  6]])

In [134]:
np.sort(arr, axis=1)

array([[ 0,  1,  5],
       [ 0,  2, 10],
       [ 6,  7,  8]])

In [135]:
# 축을 생략하면 마지막 축을 기준으로 정렬
np.sort(arr)

array([[ 0,  1,  5],
       [ 0,  2, 10],
       [ 6,  7,  8]])