# 배열의 형태(shape) 변경

## reshape()을 이용한 차원 변경
- `numpy.reshape(a, newshape)` 또는 `ndarray.reshape(newshape)`
    - 전자는 함수지향적인 방식, 후자는 객체지향적인 방식
    - a: 형태를 변경할 배열
    - newshape : 변경할 형태 설정. 
        - 원소의 개수를 유지하는 shape으로만 변환 가능하다.

In [1]:
import numpy as np
x = np.arange(20)
x.shape

(20,)

In [3]:
r1 = np.reshape(x, (4, 5))
r1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
r2 = np.reshape(x, (2, 2, 5))
r2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [6]:
r3 = x.reshape((2, 2, 5))
r3 = x.reshape(2, 2, 5)
r3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [8]:
x.reshape(4, -1)
x.reshape(2, 2, -1)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [9]:
x.reshape(1,-1)   # (20,) --> (1, 20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [14]:
x.reshape(-1, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

## 차원 늘리기(확장)
- dummy axis를 추가
    - dummy axis = size가 1인 axis

### numpy.newaxis 속성을 이용해 차원 늘리기
- size가 1인 rank를 늘릴때 사용한다. 
    - 지정한 axis에 size 1인 축을 추가한다.
- slicing에 사용하거나 indexing에 `...`과 같이 사용한다.
    - slicing의 경우 원하는 위치의 축을 늘릴 수 있다.
    - index에 ...과 사용하는 경우 첫번째나 마지막 축을 늘릴때 사용한다.
    - 거의 ...을 사용함

In [12]:
x.shape

(20,)

In [16]:
# x는 원래 1차원 배열
# np.newaxis로 더미축 axis=1을 추가 (20, 1)
r = x[:, np.newaxis]
print(r.shape)
r

(20, 1)


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [17]:
# (1, 20)
r = x[np.newaxis, :]
print(r.shape)
r

(1, 20)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

### indexing에 ... 과 같이 사용
- ndarray[..., np.newaxis]
- 첫번째 축이나 마지막 축을 늘릴때만 사용가능 (중간을 늘릴 일은 별로 없음)

In [18]:
r2 = x[..., np.newaxis]
print(r2.shape)
r2

(20, 1)


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [19]:
r2 = x[np.newaxis, ...]
r2.shape

(1, 20)

In [23]:
r3 = x[np.newaxis, ..., np.newaxis]
r3.shape

(1, 20, 1)

In [25]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
# (3, 4) -> (3, 1, 4)
r = x[:, np.newaxis, :, np.newaxis]
print(r.shape)
r

(3, 1, 4, 1)


array([[[[ 0],
         [ 1],
         [ 2],
         [ 3]]],


       [[[ 4],
         [ 5],
         [ 6],
         [ 7]]],


       [[[ 8],
         [ 9],
         [10],
         [11]]]])

In [32]:
x.shape

(3, 4)

In [36]:
x[..., np.newaxis]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

### numpy.expand_dims (배열, axis)
- 매개변수로 받은 배열에 지정한 axis의 rank를 확장한다.
- 많이 씀 !!

In [37]:
x.shape

(3, 4)

In [45]:
r = np.expand_dims(x, axis=0)
r.shape

(1, 3, 4)

In [44]:
r = np.expand_dims(x, axis=1)
r.shape

(3, 1, 4)

In [46]:
r = np.expand_dims(x, axis=2)
r.shape

(3, 4, 1)

In [47]:
r = np.expand_dims(x, axis=[1, 3])
r.shape

(3, 1, 4, 1)

## 차원 줄이기(축소)

### numpy.squeeze(배열, axis=None), 배열객체.squeeze(axis=None)
- 배열에서 지정한 축(axis)을 제거하여 차원(rank)를 줄인다.
- 제거하려는 축의 size는 1이어야 한다.
- 축을 지정하지 않으면 size가 1인 모든 축을 제거한다.
    - (3,1,1,2) => (3,2)

In [48]:
x = np.arange(12).reshape(3,1,4,1,1)
r = x.squeeze()   # axis를 생략 -> 모든 더미축을 제거
r.shape

(3, 4)

In [49]:
r = x.squeeze(axis=1)
r.shape

(3, 4, 1, 1)

In [52]:
r = x.squeeze(axis=(1,3))  # 여러 축을 지정해서 제거할 경우 -> 튜플로
r.shape

(3, 4, 1)

In [54]:
r = np.squeeze(x, (3,4))
r.shape

(3, 1, 4)

### 배열객체.flatten()
- 다차원 배열을 1차원으로 만든다.

In [55]:
print(x.shape)


(3, 1, 4, 1, 1)


In [51]:
r = x.flatten()
print(r.shape)
r

(12,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## numpy.append(), numpy.insert(), numpy.delete()
- ### append(배열, 추가할값, axis=None)
    - 배열의 마지막 index에 값을 추가
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 추가한다.
- ### insert(배열, index, 추가할값, axis=None)
    - 배열의 특정 index에 값을 추가. 
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 삽입한다.
- ### delete(배열, 삭제할index, axis=None)  
    - 배열의 삭제할 index의 값들을 삭제한다.
    - 삭제할 index는 index 또는 slice
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 삭제한다.

### append()

In [56]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [57]:
r = np.append(a, 100)   # 원본을 수정하지 않고 값을 추가한 새로운 배열을 반환
r

array([  1,   2,   3, 100])

In [58]:
r = np.append(a, [10,20,30])   # 한 번에 여러 값을 추가
r

array([ 1,  2,  3, 10, 20, 30])

In [59]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
np.append(b, 100)   # axis 지정하지 않으면 1차원으로 flatten 후 추가

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11, 100])

In [62]:
np.append(b, [[10], [20], [30]], axis=1)

array([[ 0,  1,  2,  3, 10],
       [ 4,  5,  6,  7, 20],
       [ 8,  9, 10, 11, 30]])

In [64]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
np.append(b, [[100, 200, 300, 400]], axis=0)

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [100, 200, 300, 400]])

In [68]:
# 여러 개 append 가능
np.append(b, [[100,3, 4, 5], [2,35,6,7]], axis=0)

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [100,   3,   4,   5],
       [  2,  35,   6,   7]])

### insert

In [69]:
a = np.array([1,2,3])
# np.insert(배열, index, 추가할값, axis=None)
r = np.insert(a, 1, 100)
r

array([  1, 100,   2,   3])

In [70]:
r = np.insert(a, 1, [10,45,634,34])   # 한 번에 여러 개 값 insert
r

array([  1,  10,  45, 634,  34,   2,   3])

In [71]:
l = [
    [1,1],
    [2,2],
    [3,3]
]
b = np.array(l)
print(b.shape)

(3, 2)


In [72]:
np.insert(b, 1, 1000)   # 다차원 배열에서 axis를 지정하지 않으면 1차원으로 변경 후 insert

array([   1, 1000,    1,    2,    2,    3,    3])

In [75]:
# np.insert(b, 2, [10,10], axis=0)  하나만 넣을 때는 추가할 값 1차원 배열로 줘도 됨
np.insert(b, 2, [[10,10], [11,11]], axis=0)

array([[ 1,  1],
       [ 2,  2],
       [10, 10],
       [11, 11],
       [ 3,  3]])

In [81]:
np.insert(b, 1, [5], axis=1)
np.insert(b, 1, [[5], [6]], axis=1)

array([[1, 5, 6, 1],
       [2, 5, 6, 2],
       [3, 5, 6, 3]])

### delete

In [82]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [83]:
r = np.delete(a,1)
r

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [84]:
r = np.delete(a, [1,7,8])   # 여러 개 index 삭제 시 대괄호로 (fancy indexing)
r

array([ 0,  2,  3,  4,  5,  6,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [87]:
r = np.delete(a, a[2:11])
r

array([ 0,  1, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [88]:
# np.s_[slicing문법] : 배열과 상관 없이 slicing 범위만 지정할 때 사용하는 numpy 변수
# 문법적으로는 이렇게 하는 게 좋다~
r = np.delete(a, np.s_[2:11])
r

array([ 0,  1, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [89]:
np.delete(b, 1)  # 다차원배열에서 axis를 지정하지 않으면 flatten 후 삭제 

array([1, 2, 2, 3, 3])

In [90]:
np.delete(b, 1, axis=0)

array([[1, 1],
       [3, 3]])

In [91]:
np.delete(b, 0, axis=1)

array([[1],
       [2],
       [3]])

## 배열 합치기
- ### np.concatenate(합칠 배열리스트, axis=0)
    - 여러 배열을 **축의개수(rank)**를 유지하며 합친다.
    - axis 파라미터 : 축지정
        - 지정된 축을 기준으로 합친다. 
        - default : 0
    - 합치는 배열의 축의 개수(rank) 은 같아야 한다.
    - axis속성으로 지정한 축 이외의 축의 크기가 같아야 한다.
    - 결과의 축의개수(rank)는 대상 배열의 rank와 같다.
        - 1차원끼리 합치면 1차원결과가 나옴
- ### 합칠 대상 배열의 rank가 2일 경우(행렬) 
    - vstack()
    - hstack()
    - np.concatenate()의 간단버전
- ### vstack(합칠배열리스트)
    - 수직으로 쌓는다.
    - concatenate() 의 axis=0 와 동일
    - 합칠 배열들의 열수가 같아야 한다.
- ### hstack(합칠배열리스트)
    - 수평으로 쌓는다.
    - concatenate() 의 axis=1 와 동일
    - 합칠 배열들의 행 수가 같아야 한다.

### concatenate()

- axis=0 이면 0이 늘어난다. 0을 기준으로 합치므로 (그래서 밑으로 (행이 늘어남)붙는다.)
    - 그래서 각 배열의 컬럼 수가 같아야 한다. 
- axis=1 이면 1이 늘어난다. 1을 기준으로 합치므로 (그래서 옆으로 (컬럼이 늘어남) 붙는다.)
    - 그래서 각 배열의 행수가 같아야 한다.

### vstack()
- 아래에 붙이는 개념이므로 열수가 맞아야 한다. 
- axis=0과 동일

### hstack()
- 옆으로 붙이는 것이므로 행 수가 같아야 한다.
- axis=1과 동일

## 배열 분할 하기
- ### split(배열, 분할기준, axis)
    - 지정한 축을 기준으로 배열을 나눈다.. 
    - 반환값: 분할한 narray를 가진 리스트로 리턴.
    - 배열: 분할할 배열
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
    - axis(축)
        - 분할할 기준 축을 지정한다. axis = 0 (기본) 
        - 2D의 경우 axis=0: 행 기준 분할, axis=1: 열 기준 분할
- ### vsplit(배열, 분할기준)
    - 행 기준 분할
    - split()의 axis=0과 동일
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
- ### hsplit(배열, 분할기준)
    - 열 기준 분할
    - split()의 axis=1과 동일
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
- **주의:** 분할기준을 정수(개수)로 할 경우 분할후 원소수가 같아야 한다. 

## hsplit()/vsplit()