# 배열을 파일에 저장 및 불러오기
- ## 바이너리 파일로 저장/불러오기
    - ### np.save("파일경로/파일명", 배열)
        - 배열을 raw 바이너리 형식으로 저장한다. (압축하지 않은)
        - 파일명에 확장자로 npy가 붙는다. (무조건 붙인다. abc.xxx 해도 abc.xxx.npy 로 저장)
    - ### np.load("파일경로/파일명") 
        - 파일에 저장된 배열을 불러온다.
    - ### np.savez("파일경로/파일명", 이름=배열, 이름=배열, ...)
        - 여러 개의 배열을 저장할 때 사용
        - 파일명에 확장자로 npz가 붙는다.
        - 내부적으로 압축해서 저장한다. 용량을 줄일 수 있다는 장점이 있음...
        - load() 함수로 불러오면 저장된 배열목록이 반환된다. 저장 시 지정한 이름을 이용해 조회 
- ## 텍스트 파일로 저장하고 불러오기
    - ### savetxt("파일경로/파일명", 배열 [, delimiter='(기본값=공백)']) 
        - 텍스트(문자열 타입) 형태로 저장.
        - 각 원소는 공백을 기준으로 나뉘며 delimiter 속성으로 구분자를 지정할 수 있다. (delimiter생략시 공백)
        - 1차원과 2차원 배열만 저장 가능하다. (3차원 이상은 저장이 안된다.)
    - ### loadtxt("파일경로/파일명" [,dtype=float, delimiter=공백])
        - float64 형태로 읽어옴.

In [1]:
import numpy as np

In [2]:
a = np.array([1,20,5,7,20])
b = np.ones(shape=(3,3,5))
c = np.random.normal(10, 2, size=(5,10))  # 평균=10, 표준편차=2
print(a.shape, b.shape, c.shape)

(5,) (3, 3, 5) (5, 10)


In [3]:
# binary 파일에 배열 저장
# 한 파일에 하나의 배열 저장 - save()
# 경로 - 상대경로(현재 working directory 기준 경로 - .: 현재 dir) or 절대경로(root 디렉토리부터 전체 경로)
np.save("data/array_a", a)   # data/array_a.npy
np.save("data/array_b.npy", b)
np.save("data/array.c", c)   # data/array.c.npy

In [4]:
# 불러오기 - load()
a2 = np.load("data/array_a.npy")
b2 = np.load("data/array_b.npy")
c2 = np.load("data/array.c.npy")

In [5]:
a2.shape, b2.shape, c2.shape

((5,), (3, 3, 5), (5, 10))

In [6]:
a2

array([ 1, 20,  5,  7, 20])

In [7]:
b2

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [8]:
c2

array([[11.97556245,  8.57560854,  6.89577802, 12.94819718, 10.7907999 ,
        12.01333795, 10.45453255, 11.58348866, 14.12160347, 10.93378641],
       [12.33636698, 12.58590416,  7.47282517, 13.8979922 ,  6.82103779,
         9.99725301,  8.8768986 ,  7.25744763,  5.90953362, 12.25687815],
       [10.5822191 , 12.94468308,  7.60860464,  9.23199489,  9.99991872,
        13.05723862, 13.31342684,  9.54859241,  9.37517132, 12.77929642],
       [ 9.60850694, 11.40934159,  7.92915033, 10.2048333 ,  7.99891427,
        11.43965994,  9.15233881, 10.6046498 , 10.74481452,  8.76589451],
       [ 5.64422196,  8.26365801,  7.78206919, 13.01092778,  6.15949385,
        12.85051322, 12.23230789, 10.05944517,  9.57630701, 12.12129284]])

In [9]:
c.dtype, c2.dtype

(dtype('float64'), dtype('float64'))

In [10]:
# 한 파일에 여러 개의 배열 저장 - savez()
np.savez('data/array', a=a, b=b, c=c) # array.npz

In [11]:
arrays = np.load('data/array.npz')
arrays

In [12]:
# 저장된 배열들의 이름을 조회
arrays.files

['a', 'b', 'c']

In [13]:
# 각 배열을 조회 - index 연산자를 사용
a3 = arrays['a']
b3 = arrays['b']
c3 = arrays['c']

In [14]:
a3.shape, b3.shape, c3.shape

((5,), (3, 3, 5), (5, 10))

In [15]:
# 텍스트 파일로 저장 (csv) --> 1 or 2차원 배열만 저장 가능
# savetxt
np.savetxt("data/a.csv", a)


In [18]:
a4 = np.loadtxt('data/a.csv', dtype=np.int)

In [19]:
a4

array([ 1, 20,  5,  7, 20])

In [24]:
np.savetxt("data/c.csv", c)
# delimiter 줘도 되고 안 줘도 되고... 다만 콤마로 주면 읽어올 때 명시해야 함

In [25]:
c4 = np.loadtxt('data/c.csv')
c4

array([[11.97556245,  8.57560854,  6.89577802, 12.94819718, 10.7907999 ,
        12.01333795, 10.45453255, 11.58348866, 14.12160347, 10.93378641],
       [12.33636698, 12.58590416,  7.47282517, 13.8979922 ,  6.82103779,
         9.99725301,  8.8768986 ,  7.25744763,  5.90953362, 12.25687815],
       [10.5822191 , 12.94468308,  7.60860464,  9.23199489,  9.99991872,
        13.05723862, 13.31342684,  9.54859241,  9.37517132, 12.77929642],
       [ 9.60850694, 11.40934159,  7.92915033, 10.2048333 ,  7.99891427,
        11.43965994,  9.15233881, 10.6046498 , 10.74481452,  8.76589451],
       [ 5.64422196,  8.26365801,  7.78206919, 13.01092778,  6.15949385,
        12.85051322, 12.23230789, 10.05944517,  9.57630701, 12.12129284]])